In [1]:
import torch

$b=-1,w=2$

$\hat{y}=-1+2x$

In [2]:
w = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(-1.0, requires_grad=True)

In [3]:
def forward(x):
    return w * x + b

$\hat{y}=-1+2x$

$\hat{y}=-1+2(1)$

In [8]:
x_ = torch.tensor([[1.0]])
y_hat = forward(x_)
print("The prediction is:", y_hat.item())

The prediction is: 1.0


### Class Linear

In [5]:
from torch.nn import Linear

In [6]:
torch.manual_seed(42)

In [7]:
lr = Linear(in_features=1, out_features=1, bias=True)
print("Parameters of the model b:", list(lr.parameters()))

Parameters of the model b: [Parameter containing:
tensor([[0.7645]], requires_grad=True), Parameter containing:
tensor([0.8300], requires_grad=True)]


In [9]:
from torch import nn

class LR(nn.Module):
    def __init__(self, input_size, output_size):
        super(LR, self).__init__()
        self.linear = Linear(input_size, output_size)

    def forward(self, x):
        return self.linear(x)

In [15]:
lr = LR(1, 1)
print("Parameters of the model b:", list(lr.parameters()))
print("Linear Model: ", lr.linear)

Parameters of the model b: [Parameter containing:
tensor([[-0.4869]], requires_grad=True), Parameter containing:
tensor([0.5873], requires_grad=True)]
Linear Model:  Linear(in_features=1, out_features=1, bias=True)


In [16]:
x = torch.tensor([[1.0]])
y_hat = lr(x)
print("The prediction is:", y_hat.item())

The prediction is: 0.10042762756347656
